FORMAT: 1A
HOST: https://air-quality-forecast.weather.mg/

# Air Quality Forecast Service

### Authentication

All endpoints are **secured** using OAuth2 authorization protocol with transmitting data over HTTPS.
The authorization flows are described here [authorization flow](http://oauthbible.com/#oauth-2-two-legged)

#### Client Credentials

Before getting an access to any endpoints, need to obtain **client id** and **client secret**.
For achieving this, please use [request form](https://meteogroup.zendesk.com/hc/en-gb/requests/new?ticket_form_id=64951).

#### Authorization Token

Once you have your client credentials (Client-ID + Password), you can request a token on
[Authorization server](https://auth.weather.mg/oauth/token?grant_type=client_credentials with http basic auth).

The token will be in the return message, encrypted with a key from the authorization service.

It will contain the client-ID, scopes and expiration date.
The token is only a valid for a limited time, after this it will expired and you have to request a new token again.

#### Using Authorization Token

HTTP GET request to the endpoints needs to provide Authorization Token into **Authorization** HTTP Header.
More information about JWT token might be found here: https://en.wikipedia.org/wiki/JSON_Web_Token.

HTTP Header: **Authorization** : **Bearer {ENCRYPTED TOKEN HERE}**

The Authorization token contains the Scopes which the client is allowed to have.
**air-quality-forecast** is the scope which allows to request Air Quality Forecast Service.

### Search air quality forecasts for location [GET /search?locatedAt={locatedAt}&fields={fields}]

This endpoint is deprecated and will be removed in the near future.

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.EkN-DOsnsuRjRO6BxXemmJDm3HbxrbRzXglbN2S4sOkopdU4IsDxTI8jO19W_A4K8ZPJijNLis4EZsHeY559a4DFOd50_OqgHGuERTqYZyuhtF39yxJPAjUESwxk2J5k_4zM3O-vtd1Ghyo4IbqKKSy6J9mTniYJPenn5-HIirE

    + Parameters
        + locatedAt: `-2.2323,47.4593` (string, required) - longitude,latitude;
        + fields: `airPollutionIndex` (string, required) - comma separated list of [airPollutionIndex,pollenIndex] or single value
    
+ Response 200 (application/json)
    
    Returns forecasts for today + 4 days.
    
    + Body
        
            {
                "forecasts": [
                    {
                      "forecastLocation": [ -2.2323, 47.4593 ],
                      "publishedAt": "2017-01-22T06:00:00Z",
                      "validFrom": "2017-01-22T00:00:00Z",
                      "validUntil": "2017-01-23T00:00:00Z",
                      "period": "PT24H",
                      "airPollutionIndex": 1,
                      "type": "pollution"
                    },
                    {
                      "forecastLocation": [ -2.2323, 47.4593 ],
                      "publishedAt": "2017-01-23T06:00:00Z",
                      "validFrom": "2017-01-23T00:00:00Z",
                      "validUntil": "2017-01-24T00:00:00Z",
                      "period": "PT24H",
                      "airPollutionIndex": 2,
                      "type": "pollution"
                    },
                    {
                      "forecastLocation": [ -2.2323, 47.4593 ],
                      "publishedAt": "2017-01-24T06:00:00Z",
                      "validFrom": "2017-01-24T00:00:00Z",
                      "validUntil": "2017-01-25T00:00:00Z",
                      "period": "PT24H",
                      "airPollutionIndex": 3,
                      "type": "pollution"
                    },
                    {
                      "forecastLocation": [ -2.2323, 47.4593 ],
                      "publishedAt": "2017-01-25T06:00:00Z",
                      "validFrom": "2017-01-25T00:00:00Z",
                      "validUntil": "2017-01-26T00:00:00Z",
                      "period": "PT24H",
                      "airPollutionIndex": 4,
                      "type": "pollution"
                    },
                    {
                      "forecastLocation": [ -2.2323, 47.4593 ],
                      "publishedAt": "2017-01-26T06:00:00Z",
                      "validFrom": "2017-01-26T00:00:00Z",
                      "validUntil": "2017-01-27T00:00:00Z",
                      "period": "PT24H",
                      "airPollutionIndex": 5,
                      "type": "pollution"
                    }
                ]
            }

### Search air pollution forecasts for location [GET /pollution/search?locatedAt={locatedAt}&fields={fields}]

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.EkN-DOsnsuRjRO6BxXemmJDm3HbxrbRzXglbN2S4sOkopdU4IsDxTI8jO19W_A4K8ZPJijNLis4EZsHeY559a4DFOd50_OqgHGuERTqYZyuhtF39yxJPAjUESwxk2J5k_4zM3O-vtd1Ghyo4IbqKKSy6J9mTniYJPenn5-HIirE

    + Parameters
        + locatedAt: `-0.11,51.51` (string, required) - longitude,latitude;
        + fields: `airPollutionIndex,publishedAt` (string, required) - comma separated list of [airPollutionIndex,publishedAt] or single value;
        + timeZone: `Europe/Paris` (string, optional) - Time zone refers to the IANA Time Zone Database (TZDB).

+ Response 200 (application/json)

    Returns air pollution forecasts for today + 4 days.

    + Body

            {
              "forecasts": [
                {
                  "period": "PT24H",
                  "validFrom": "2017-05-10T00:00:00Z",
                  "validUntil": "2017-05-11T00:00:00Z",
                  "forecastLocation": [ -0.1248, 51.5081 ],
                  "airPollutionIndex": 3,
                  "publishedAt": "2017-05-10T05:00:00Z"
                },
                {
                  "period": "PT24H",
                  "validFrom": "2017-05-11T00:00:00Z",
                  "validUntil": "2017-05-12T00:00:00Z",
                  "forecastLocation": [ -0.1248, 51.5081 ],
                  "airPollutionIndex": 5,
                  "publishedAt": "2017-05-10T05:00:00Z"
                },
                {
                  "period": "PT24H",
                  "validFrom": "2017-05-12T00:00:00Z",
                  "validUntil": "2017-05-13T00:00:00Z",
                  "forecastLocation": [ -0.1248, 51.5081 ],
                  "airPollutionIndex": 3,
                  "publishedAt": "2017-05-10T05:00:00Z"
                },
                {
                  "period": "PT24H",
                  "validFrom": "2017-05-13T00:00:00Z",
                  "validUntil": "2017-05-14T00:00:00Z",
                  "forecastLocation": [ -0.1248, 51.5081 ],
                  "airPollutionIndex": 3,
                  "publishedAt": "2017-05-10T05:00:00Z"
                },
                {
                  "period": "PT24H",
                  "validFrom": "2017-05-14T00:00:00Z",
                  "validUntil": "2017-05-15T00:00:00Z",
                  "forecastLocation": [ -0.1248, 51.5081 ],
                  "airPollutionIndex": 3,
                  "publishedAt": "2017-05-10T05:00:00Z"
                }
              ]
            }

### Search pollen forecasts for location [GET /pollen/search?locatedAt={locatedAt}&fields={fields}]

Pollen forecast available only on United Kingdom. When you try querying outside UK, you are receive response with status code `400 Bad Request`.
Available pollen forecast separated on 16 regions. The `pollenForecastRegion` and `pollenForecastRegionName` parameters refers on table, see below:

Id  Name
--  ------------------------------
DG	SW Scotland, Lothian Borders
EE 	East of England
EM	East Midlands
GR	Grampian
HE 	Highlands & Eilean Siar
NE	North East England
NI	Northern Ireland
NW	North West England
OS	Orkney & Shetland
SE	London & South East England
ST 	Strathclyde
SW	South West England
TA	Central, Tayside & Fife
WL	Wales
WM	West Midlands
YH	Yorkshire & Humber

The `pollenIndex` parameters can be one of the following levels: Low, Moderate, High, Veryhigh

+ Request

    + Headers

            Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.EkN-DOsnsuRjRO6BxXemmJDm3HbxrbRzXglbN2S4sOkopdU4IsDxTI8jO19W_A4K8ZPJijNLis4EZsHeY559a4DFOd50_OqgHGuERTqYZyuhtF39yxJPAjUESwxk2J5k_4zM3O-vtd1Ghyo4IbqKKSy6J9mTniYJPenn5-HIirE

    + Parameters
        + locatedAt: `-0.11,51.51` (string, required) - longitude,latitude;
        + fields: `pollenForecastRegionName,issuedAt,pollenIndex` (string, required) - comma separated list of [pollenForecastRegionName,issuedAt,pollenIndex] or single value;
        + timeZone: `Europe/Paris` (string, optional) - Time zone refers to the IANA Time Zone Database (TZDB).

+ Response 200 (application/json)

    Returns pollen forecasts for today + 4 days.

    + Body

            {
              "forecasts": [
                {
                  "period": "PT24H",
                  "validFrom": "2017-05-09T23:00:00Z",
                  "validUntil": "2017-05-10T23:00:00Z",
                  "pollenForecastRegion": "SE",
                  "pollenForecastRegionName": "London & South East England",
                  "pollenIndex": "Moderate",
                  "issuedAt": "2017-05-10T04:45:57Z"
                },
                {
                  "period": "PT24H",
                  "validFrom": "2017-05-10T23:00:00Z",
                  "validUntil": "2017-05-11T23:00:00Z",
                  "pollenForecastRegion": "SE",
                  "pollenForecastRegionName": "London & South East England",
                  "pollenIndex": "Moderate",
                  "issuedAt": "2017-05-10T04:45:57Z"
                },
                {
                  "period": "PT24H",
                  "validFrom": "2017-05-11T23:00:00Z",
                  "validUntil": "2017-05-12T23:00:00Z",
                  "pollenForecastRegion": "SE",
                  "pollenForecastRegionName": "London & South East England",
                  "pollenIndex": "Moderate",
                  "issuedAt": "2017-05-10T04:45:57Z"
                },
                {
                  "period": "PT24H",
                  "validFrom": "2017-05-12T23:00:00Z",
                  "validUntil": "2017-05-13T23:00:00Z",
                  "pollenForecastRegion": "SE",
                  "pollenForecastRegionName": "London & South East England",
                  "pollenIndex": "Moderate",
                  "issuedAt": "2017-05-10T04:45:57Z"
                },
                {
                  "period": "PT24H",
                  "validFrom": "2017-05-13T23:00:00Z",
                  "validUntil": "2017-05-14T23:00:00Z",
                  "pollenForecastRegion": "SE",
                  "pollenForecastRegionName": "London & South East England",
                  "pollenIndex": "Moderate",
                  "issuedAt": "2017-05-10T04:45:57Z"
                }
              ]
            }

