FORMAT: 1A

Station Metadata API
=============================


# General information

This is technical documentation for the Station Metadata API.
This document uses [API blueprint format](https://apiblueprint.org/documentation/).

Station Metadata is a service to get information about stations in GeoJSON format. 

### Authentication

All endpoints are **secured** using OAuth2 authorization protocol with transmitting data over HTTPS.
The authorization flows are described here [authorization flow](http://oauthbible.com/#oauth-2-two-legged)

#### Client Credentials

Before getting an access to any endpoints, need to obtain **client id** and **client secret**.
For achieving this, please use [request form](https://meteogroup.zendesk.com/hc/en-gb/requests/new?ticket_form_id=64951).

#### Authorization Token

Once you have your client credentials (Client-ID + Password), you can request a token on
[Authorization server](https://auth.weather.mg/oauth/token?grant_type=client_credentials).

The token will be in the return message, encrypted with a key from the authorization service.

It will contain the client-ID, scopes and expiration date.
The token is only a valid for a limited time, after this it will expired and you have to request a new token again.

#### Using Authorization Token

HTTP GET request to the endpoints needs to provide Authorization Token into **Authorization** HTTP Header.
More information about JWT token might be found here: https://en.wikipedia.org/wiki/JSON_Web_Token.

HTTP Header: **Authorization** : **Bearer {ENCRYPTED TOKEN HERE}**

The Authorization token contains the Scopes which the client is allowed to have.
**station-metadata** is the scope which allows to request Point Observation Service.

#### Cache control headers:

if data unchanged since this date using the If-Modified-Since request header
the server will return with an empty body with the 304 response code.

### Backward compatibility

Every endpoint may add one or more response parameters in the future.
Clients should ignore unknown parameters, to avoid technical issues.

#Stations Metadata API

## Retrieve station metadata [/stations]

For any request all the GET HTTP parameters are optional.

+ Parameters
    + locatedWithin:
        - {"type":"bbox","coordinates":[[lon,lat],[lon,lat]]} (string, optional) - top left and bottom right coordinates that construct bounding box;
        - {"type":"polygon","coordinates":[[-10,10],[10,5],[-5,-5]]} - polygon coordinates.
    + accessVisibility: `public` (string, optional) - parameter that filter **public** or **private** stations to show;
    + providerOrType: `WMO` (string, optional) - describes data provider or type;
    + type: `SKI_RESORT` (string, optional) - describes type of station place;
    + hasForecastData: `true` (boolean, optional) - show only stations that provide forecasts;
    + hasObservationData: `true` (boolean, optional) - show only stations that provide observations;
    + countryIsoCode: `DE` (string, optional) - filter stations by country ISO code.

### Get a stations metadata for Germany [GET]

####An example
'https://station-metadata.weather.mg/stations?countryIsoCode=DE&hasObservationData=true'
'https://station-metadata.weather.mg/stations?locatedWithin={"type":"polygon","coordinates":[[-10,10],[10,5],[-5,-5]]}'
'https://station-metadata.weather.mg/stations?locatedWithin={"type":"bbox","coordinates":[[-10,80],[10,5]]}'

+ Response 200 (application/json)

    + Headers

            Content-Type: application/json
            Cache-Control: max-age=86400
            Last-Modified: Mon, 10 Jul 2017 08:37:16 GMT
    
    + Body
        
            {
                "type": "FeatureCollection",
                "features": [
                    {
                        "type": "Feature",
                        "properties": {
                            "accessVisibility": "public",
                            "icaoCode": "EDXW",
                            "countryIsoCode": "DE",
                            "hasForecastData": true,
                            "wmoCountryId": 69,
                            "meteoGroupStationId": 10018,
                            "name": "Westerland/Sylt",
                            "providerStationId": "GWT",
                            "providerOrType": "AVIATION",
                            "hasObservationData": true,
                            "stationTimeZoneName": "Europe/Berlin"
                        },
                        "geometry": {
                            "type": "Point",
                            "coordinates": [
                                8.35,
                                54.9167,
                                20
                            ]
                        }
                    },
                    {
                        "type": "Feature",
                        "properties": {
                            "accessVisibility": "public",
                            "countryIsoCode": "DE",
                            "hasForecastData": true,
                            "wmoCountryId": 69,
                            "meteoGroupStationId": 10020,
                            "name": "List/Sylt",
                            "providerOrType": "WMO/DWD",
                            "hasObservationData": true,
                            "stationTimeZoneName": "Europe/Berlin"
                        },
                        "geometry": {
                            "type": "Point",
                            "coordinates": [
                                8.4125,
                                55.0112,
                                26
                            ]
                        }
                    }
                ]
            }
