FORMAT: 1A

Weather API
=============================


# General information

This technical document was created for developers who are creating applications based on weather data provided by this API.
This document is using [API blueprint format](https://apiblueprint.org/documentation/).

### Authentication

All endpoints are **secured** with HTTP basic authorization and data are transmitted over HTTPS protocol.
If you want to get access please use [request form](https://meteogroup.zendesk.com/hc/en-gb/requests/new?ticket_form_id=64951).

### Backward compatibility

Every endpoint may add one or more response parameters in the future.
Clients should ignore unknown parameters, to avoid technical issues.


# Group Observation

## Retrieve weather observation [/search?locatedAt={locatedAt}&fields={fields}&observedFrom={observedFrom}&observedUntil={observedUntil}&observedPeriod={observedPeriod}]

#### Example
`https://point-observation.weather.mg/search?locatedAt=52,13&fields=meteoGroupStationId,airTemperatureInCelsius,windGustInMeterPerSecond&observedPeriod=PT0S,PT1H`

### Search for observation data from weather stations for multiple given locations or given station ID [GET]

For any requested location a relevant station is searched.
The searching algorithm stops at a maximum distance of 100km (between requested location and station)
and ensures that at least air temperature parameter is available for a station.
By default, the latest known weather observation data from a relevant station is returned.
If observedFrom and observedUntil are missing then application sets observedFrom as current time minus 3 hours and observedUntil as current time.
if observedFrom is not missing and observedUntil is missing then application sets  observedUntil as current time plus 3 days.
There is possible to use station ID parameter instead of location parameter. in order to get observation for concrete station.

*Meteorological hints*

There are two basic observation periods, one hour and one moment.
Each weather parameter refers implicitly to one or another time period of measurement.
For example air temperature is measured at one moment in time.
Whereas max air temperature is typically measured inside a weather station and just reported once an hour.
Hence it refers to an hour of observation period.
In the response JSON document the weather parameters will be associated with their according period.

*Technical hints*

All timestamps and time periods/durations follow ISO8601 standard notation.
For example 'PT1H' refers to one hour and 'PT0S' refers to one moment.
For convenience reasons, a single location can be requested, but the response always returns a collection.
For multiple locations, its recommended to just use the point compression.
The observations in the response collection are "flat" to allow easy streaming and filtering on client side.
The observations in the response are ordered ascending by field 'observedFrom'.

*Fields mapping*

Common names of filed which can be included in all periods: meteoGroupStationId, meteoGroupStationName, stationLocation, stationTimeZoneName

Here are relationship between observation periods and fields appropriately:

- **PT0S** - airTemperatureInCelsius, airTemperatureInFahrenheit, feelsLikeTemperatureInCelsius, feelsLikeTemperatureInFahrenheit, airPressureInHpa,
             windSpeedInMeterPerSecond, windSpeedInKilometerPerHour, windSpeedInMilePerHour, windSpeedInBeaufort, windSpeedInKnot, windDirectionInDegree,
             dewPointTemperatureInCelsius, dewPointTemperatureInFahrenheit, relativeHumidityInPercent100based, effectiveCloudCoverInOcta, visibilityInMeter,
             visibilityInKilometers, visibilityInNauticalMile, visibilityInStatuteMile, presentWeather, weatherSymbol
- **PT1H** - windGustInMeterPerSecond, windGustInKilometerPerHour, windGustInMilePerHour, windGustInBeaufort, windGustInKnot, precipitationAmountInMillimeter, precipitationAmountInInch
- **PT3H** - pressureTendencyCode, pressureChangeInHectoPascal
- **PT12H** - temperatureMaxInDegreeCelsius, temperatureMaxInFahrenheit, temperatureMinInDegreeCelsius, temperatureMinInFahrenheit
- **PT24H** - precipitationAmountInMillimeter, precipitationAmountInInch, sunshineDurationInHours

+ Parameters
    + stationId: `3007237` (string, optional) - station id
    + locatedAt: `-2.2323,47.4593` (string, optional) - longitude,latitude; can occur multiple times for multiple stations
    + locatedAt: `joionluqqFvwqmo629nC` (string, optional) - compressed list of station locations, using Microsoft Point Compression Algorithm, is efficient for up to 400 locations,
    + fields: `meteoGroupStationId,meteoGroupStationName,stationLocation,stationTimeZoneName,sunshineDurationInMinutes,airTemperatureInCelsius,windGustInKnots,windSpeedInKnots...` (string, required) - comma separated list of parameters to be contained inside response. All possible names are present in section 'Fields names'
    + observedFrom: `2016-10-15T08:00:00Z` (string, optional) - ISO8601 timestamp notation, means incl. this timestamp; always provide a time offset, e.g. 'Z' for UTC; optional: a request may provide correct offset (so that server can convert to UTC).
    + observedUntil: `2016-10-15T09:00:00Z` (string, optional) - ISO8601 timestamp notation, means incl. this timestamp; always provide a time offset, e.g. 'Z' for UTC; optional: a request may provide correct offset (so that server can convert to UTC).
    + observedPeriod: `PT0S,PT1H,PT3H,PT12H,PT24H` (string, required) - comma separated list of periods to be retrieved. use ISO8601 time duration notation. PT0S refers to observations at a moment in time. PT1H applies one hour aggregation.

+ Response 200 (application/json)

    + Headers

            X-Request-Calls-Per-Interval: 4711
            E-Tag: "x234dff"
            Cache-Control: max-age=3628800

    + Body

          {
            "observations": [
              {
                "locatedAt": [
                  -2.2323,
                  47.4593
                ],
                "meteoGroupStationId": "3007237",
                "meteoGroupStationName": "Pleucadeuc",
                "stationLocation": [
                  -2.2323,
                  47.4593
                ],
                "stationTimeZoneName": "Europe/Prague",
                "observedFrom": "2016-10-15T08:00:00Z",
                "observedUntil": "2016-10-15T08:00:00Z",
                "observedPeriod": "PT0S",
                "airTemperatureInCelsius": 3.4,
                "airTemperatureInFahrenheit": 38.12,
                "feelsLikeTemperatureInCelsius": 3.9,
                "feelsLikeTemperatureInFahrenheit": 39.02,
                "airPressureInHpa": 1005.5,
                "windSpeedInMeterPerSecond": 0.5144445,
                "windSpeedInKilometerPerHour": 1.852,
                "windSpeedInMilePerHour": 1.1507794,
                "windSpeedInBeaufort": 1,
                "windSpeedInKnot": 0.99999976,
                "windDirectionInDegree": 210,
                "dewPointTemperatureInCelsius": 3,
                "dewPointTemperatureInFahrenheit": 37.4,
                "relativeHumidityInPercent100based": 97,
                "effectiveCloudCoverInOcta": 5,
                "visibilityInMeter": 2000,
                "visibilityInKilometers": 2,
                "visibilityInNauticalMile": 1.0799999,
                "visibilityInStatuteMile": 1.2427424,
                "presentWeather": "2",
                "weatherSymbol": 100000
              },
              {
                "locatedAt": [
                  -2.2323,
                  47.4593
                ],
                "meteoGroupStationId": "3007237",
                "meteoGroupStationName": "Pleucadeuc",
                "stationLocation": [
                  -2.2323,
                  47.4593
                ],
                "stationTimeZoneName": "Europe/Prague",
                "observedFrom": "2016-10-15T07:00:00Z",
                "observedUntil": "2016-10-15T08:00:00Z",
                "observedPeriod": "PT1H",
                "windGustInMeterPerSecond": 0.8231112,
                "windGustInKilometerPerHour": 2.9632,
                "windGustInMilePerHour": 1.8412471,
                "windGustInBeaufort": 1,
                "windGustInKnot": 1.5999997,
                "precipitationAmountInMillimeter": 0,
                "precipitationAmountInInch": 0
              },
              {
                "locatedAt": [
                  -2.2323,
                  47.4593
                ],
                "meteoGroupStationId": "3007237",
                "meteoGroupStationName": "Pleucadeuc",
                "stationLocation": [
                  -2.2323,
                  47.4593
                ],
                "stationTimeZoneName": "Europe/Prague",
                "observedFrom": "2016-10-15T05:00:00Z",
                "observedUntil": "2016-10-15T08:00:00Z",
                "observedPeriod": "PT3H",
                "pressureChangeInHectoPascal": 2,
                "pressureTendencyCode": 1
              },
              {
                "locatedAt": [
                  -2.2323,
                  47.4593
                ],
                "meteoGroupStationId": "3007237",
                "meteoGroupStationName": "Pleucadeuc",
                "stationLocation": [
                  -2.2323,
                  47.4593
                ],
                "stationTimeZoneName": "Europe/Prague",
                "observedFrom": "2016-10-14T20:00:00Z",
                "observedUntil": "2016-10-15T08:00:00Z",
                "observedPeriod": "PT12H",
                "temperatureMaxInDegreeCelsius": 3.7,
                "temperatureMaxInFahrenheit": 38.66,
                "temperatureMinInDegreeCelsius": 3.1,
                "temperatureMinInFahrenheit": 37.58
              },
              {
                "locatedAt": [
                  -2.2323,
                  47.4593
                ],
                "meteoGroupStationId": "3007237",
                "meteoGroupStationName": "Pleucadeuc",
                "stationLocation": [
                  -2.2323,
                  47.4593
                ],
                "stationTimeZoneName": "Europe/Prague",
                "observedFrom": "2016-10-14T08:00:00Z",
                "observedUntil": "2016-10-15T08:00:00Z",
                "observedPeriod": "PT24H",
                "precipitationAmountInMillimeter": 0.2,
                "precipitationAmountInInch": 0.008,
                "sunshineDurationInHours": 12
              },
              {
                "locatedAt": [
                  -2.2323,
                  47.4593
                ],
                "meteoGroupStationId": "3007237",
                "meteoGroupStationName": "Pleucadeuc",
                "stationLocation": [
                  -2.2323,
                  47.4593
                ],
                "stationTimeZoneName": "Europe/Prague",
                "observedFrom": "2016-10-15T09:00:00Z",
                "observedUntil": "2016-10-15T09:00:00Z",
                "observedPeriod": "PT0S",
                "airTemperatureInCelsius": 2.6,
                "airTemperatureInFahrenheit": 36.68,
                "feelsLikeTemperatureInCelsius": 3.1,
                "feelsLikeTemperatureInFahrenheit": 37.58,
                "airPressureInHpa": 1005.5,
                "windSpeedInMeterPerSecond": 0.5144445,
                "windSpeedInKilometerPerHour": 1.852,
                "windSpeedInMilePerHour": 1.1507794,
                "windSpeedInBeaufort": 1,
                "windSpeedInKnot": 0.99999976,
                "windDirectionInDegree": 230,
                "dewPointTemperatureInCelsius": 2.3,
                "dewPointTemperatureInFahrenheit": 36.14,
                "relativeHumidityInPercent100based": 98,
                "effectiveCloudCoverInOcta": 5,
                "visibilityInMeter": 2000,
                "visibilityInKilometers": 2,
                "visibilityInNauticalMile": 1.0799999,
                "visibilityInStatuteMile": 1.2427424,
                "presentWeather": "2",
                "weatherSymbol": 100000
              },
              {
                "locatedAt": [
                  -2.2323,
                  47.4593
                ],
                "meteoGroupStationId": "3007237",
                "meteoGroupStationName": "Pleucadeuc",
                "stationLocation": [
                  -2.2323,
                  47.4593
                ],
                "stationTimeZoneName": "Europe/Prague",
                "observedFrom": "2016-10-15T08:00:00Z",
                "observedUntil": "2016-10-15T09:00:00Z",
                "observedPeriod": "PT1H",
                "windGustInMeterPerSecond": 0.97744447,
                "windGustInKilometerPerHour": 3.5188,
                "windGustInMilePerHour": 2.1864808,
                "windGustInBeaufort": 1,
                "windGustInKnot": 1.8999995,
                "precipitationAmountInMillimeter": 0,
                "precipitationAmountInInch": 0
              },
              {
                "locatedAt": [
                  -2.2323,
                  47.4593
                ],
                "meteoGroupStationId": "3007237",
                "meteoGroupStationName": "Pleucadeuc",
                "stationLocation": [
                  -2.2323,
                  47.4593
                ],
                "stationTimeZoneName": "Europe/Prague",
                "observedFrom": "2016-10-15T06:00:00Z",
                "observedUntil": "2016-10-15T09:00:00Z",
                "observedPeriod": "PT3H",
                "pressureChangeInHectoPascal": 2,
                "pressureTendencyCode": 1
              },
              {
                "locatedAt": [
                  -2.2323,
                  47.4593
                ],
                "meteoGroupStationId": "3007237",
                "meteoGroupStationName": "Pleucadeuc",
                "stationLocation": [
                  -2.2323,
                  47.4593
                ],
                "stationTimeZoneName": "Europe/Prague",
                "observedFrom": "2016-10-14T21:00:00Z",
                "observedUntil": "2016-10-15T09:00:00Z",
                "observedPeriod": "PT12H",
                "temperatureMaxInDegreeCelsius": 2.5,
                "temperatureMaxInFahrenheit": 36.5,
                "temperatureMinInDegreeCelsius": 2.8,
                "temperatureMinInFahrenheit": 37.04
              },
              {
                "locatedAt": [
                  -2.2323,
                  47.4593
                ],
                "meteoGroupStationId": "3007237",
                "meteoGroupStationName": "Pleucadeuc",
                "stationLocation": [
                  -2.2323,
                  47.4593
                ],
                "stationTimeZoneName": "Europe/Prague",
                "observedFrom": "2016-10-14T09:00:00Z",
                "observedUntil": "2016-10-15T09:00:00Z",
                "observedPeriod": "PT24H",
                "precipitationAmountInMillimeter": 0.1,
                "precipitationAmountInInch": 0.004,
                "sunshineDurationInHours": 12
              }
            ]
          }

# Group Forecast

## Retrieve weather forecast [/search?locatedAt={locatedAt}&fields={fields}&validPeriod={validPeriod}&validFrom={validFrom}{&validUntil}]   to be FIXED ...

#### Example
`https://point-forecast.weather.mg/search?locatedAt=53,13`  to be FIXED ...

### Search for forecast data from weather stations for multiple given locations [GET]

For any requested location a relevant station is searched.
The searching algorithm stops at a maximum distance of 100km (between requested location and station).
By default, the latest known weather forecast data from a relevant station is returned.

*Meteorological hints*

The forecasted parameters always have a time period associated, which is typically one hour and one moment.
Each weather parameter refers implicitly to one or another time period within a forecast.
For example air temperature is forecasted for one moment in time.
Whereas max air temperature is typically forecasted for a period of one our.
There are other forecast periods possible, where parameters than are aggregated among e.g. 12 hours.
In the response JSON document the weather parameters will be associated with their according period.

*Technical hints*

All timestamps and time periods/durations follow ISO8601 standard notation.
For example 'PT1H' refers to one hour and 'PT0S' refers to one moment.
For convinience reasons, a single location can be requested, but the response always returns a collection.
For multiple locations, its recommended to just use the point compression.
The observations in the response collection are "flat" to allow easy streaming and filtering on client side.
The observations in the response are ordered ascending by field 'validFrom'.

### Forecasted weather for a given *latitude* and *longitude* [GET]

+ Parameters
    + locatedAt: `13.37788,52.5337` (string, required) - longitude,latitude; can occur multiple times for multiple locations
    + locatedAt: `joionluqqFvwqmo629nC` (string, optional) - compressed list of station locations, using Microsoft Point Compression Algorithm, is efficient for up to 400 locations   to be FIXED ...
    + fields: `airTemperatureInCelsius,dewPointTemperatureInFahrenheit,dewPointTemperatureInKelvin` (string, required) - comma separated list of parameters to be contained inside response    to be FIXED ...
    + validFrom: `2016-10-13T11:00:00Z` (string, optional) - ISO8601 timestamp notation, means incl. this timestamp; always provide a time offset, e.g. 'Z' for UTC; optional: a request may provide correct offset (so that server can convert to UTC).
    + validUntil: `2016-10-13T15:00:00Z` (string, optional) - ISO8601 timestamp notation, means incl. this timestamp; always provide a time offset, e.g. 'Z' for UTC; optional: a request may provide correct offset (so that server can convert to UTC).
    + validPeriod: `PT0S,PT1H` (string, required) - comma separated list of periods to be retrieved. use iso8601 time duration notation. PT1H refers one hour forecast periods.

+ Response 200 (application/json)

    + Headers

            X-Request-Calls-Per-Interval: 4712
            E-Tag: "a987dff"
            Cache-Control: max-age=600

    + Body

            {
                "forecasts" : [
                    {
                        "locatedAt" : [13.37788, 52.5337],
                        "meteoGroupStationId" : "abcd1234ef5678",
                        "meteoGroupStationName" : "Berlin Dahlem",
                        "stationLocation" : [13.36612, 52.1234],
                        "stationTimeZoneName" : "Europe/Berlin",
                        "validFrom": "2016-08-25T14:00:00Z",
                        "validUntil": "2016-08-25T14:00:00Z",
                        "validPeriod": "PT0S",
                        "airTemperatureInCelsius": 15.8,
                        "dewPointTemperatureInCelsius": 15.8,
                        "airPressureInHpa": 1012.9,
                        "effectiveCloudCoverInOcta": 3,
                        "precipitationIntensityInMillimeter": 0,
                        "windSpeedInKnots": 3
                    },
                    {
                        "locatedAt" : [13.37788, 52.5337],
                        "meteoGroupStationId" : "abcd1234ef5678",
                        "meteoGroupStationName" : "Berlin Dahlem",
                        "stationLocation" : [13.36612, 52.1234],
                        "stationTimeZoneName" : "Europe/Berlin",
                        "validFrom": "2016-08-25T14:00:00Z",
                        "validUntil": "2016-08-25T15:00:00Z",
                        "validPeriod": "PT1H",
                        "minAirTemperatureInCelsius": 13,
                        "maxAirTemperatureInCelsius": 16,
                        "sunshineDurationInMinutes": 23,
                        "precipitationAmountInMillimeter": 0,
                        "windGustInKnots": 5
                    },
                    {
                        "locatedAt" : [13.37788, 52.5337],
                        "meteoGroupStationId" : "abcd1234ef5678",
                        "meteoGroupStationName" : "Berlin Dahlem",
                        "stationLocation" : [13.36612, 52.1234],
                        "stationTimeZoneName" : "Europe/Berlin",
                        "validFrom": "2016-08-25T15:00:00Z",
                        "validUntil": "2016-08-25T15:00:00Z",
                        "validPeriod": "PT0S",
                        "airTemperatureInCelsius": 14.2,
                        "dewPointTemperatureInCelsius": 14.1,
                        "airPressureInHpa": 1011,
                        "effectiveCloudCoverInOcta": 4,
                        "precipitationIntensityInMillimeter": 0,
                        "windSpeedInKnots": 2
                    },
                    {
                        "locatedAt" : [13.37788, 52.5337],
                        "meteoGroupStationId" : "abcd1234ef5678",
                        "meteoGroupStationName" : "Berlin Dahlem",
                        "stationLocation" : [13.36612, 52.1234],
                        "stationTimeZoneName" : "Europe/Berlin",
                        "validFrom": "2016-08-25T15:00:00Z",
                        "validUntil": "2016-08-25T16:00:00Z",
                        "validPeriod": "PT1H",
                        "minAirTemperatureInCelsius": 14,
                        "maxAirTemperatureInCelsius": 16,
                        "sunshineDurationInMinutes": 18,
                        "precipitationAmountInMillimeter": 0,
                        "windGustInKnots": 4
                    }
                ]
            }


# Group Warning

## Retrieve severe weather warnings [/warnings?location={latitudeInDegree,longitudeInDegree}]

### Example
`https://api.weather.mg/forecast?location=53,13`

### Severe Weather Warnings [GET]

THIS IS A DRAFT.

+ Parameters
    + latitudeInDegree: `52.13` (number, required)                - latitude in degree numeric format and in range <-90,90> eg. -85.541, 5.32
    + longitudeInDegree: `13.2` (number, required)                - longitude in degree numeric format and in range <-180,180> eg. -123.454, 179.864

+ Request

    + Headers

            X-Authentication: <API-Key>
            X-TraceId: <Trace-Id>

+ Response 200 (application/json)

    + Headers

            X-Request-Calls-Per-Interval: 4712
            E-Tag: "a987dff"
            Cache-Control: max-age=600

    + Body

            {
                "location" : {
                    "latitude": 52.5337,
                    "longitude": 13.37788,
                },
                "warningId": "1234-5678",
                "issueAt": "2016-08-03T00:00:00+02:00",
                "validAt": "2016-08-03T00:00:00+02:00",
                "warningSeverity": "HIGH",
                "affectedRegion": {
                    "name": "London"
                }
            }


# Data Structures

## Total Cloud Cover (number)

This symbolic digit shall embrace the total fraction of the celestial dome covered by clouds irrespective of their genus.
(WMO akronym 'N')

    Value | Meaning
    ------|---------
    0 | 0
    1 | 1 okta or less, but not zero
    2 | 2 oktas
    3 | 3 oktas
    4 | 4 oktas
    5 | 5 oktas
    6 | 6 oktas
    7 | 7 oktas
    8 | 8 oktas
    9 | Sky obscured by fog and/or other meteorological phenomena
