FORMAT: 1A

Weather API
=============================

Do you want to send [feedback](https://meteogroup.zendesk.com/hc/en-gb/requests/new?ticket_form_id=64951)?

[Roadmap for Weather API](https://github.com/MeteoGroup/weather-api/tree/roadmap)

# General information

This technical document was created for developers who are creating applications based on weather data provided by this API.


The Weather API resolves weather data based on location specified by latitude and longitude coordinates.
For weather parameters prediction API offer ["forecast" endpoint](#forecast) and for weather history parameters API offer ["observation" endpoint](#observation).


This document is using [API blueprint format](https://apiblueprint.org/documentation/).

All endpoints are **secured** with HTTP basic authorization and data are transmitted over HTTPS protocol.
If you want to get access please use [request form](https://meteogroup.zendesk.com/hc/en-gb/requests/new?ticket_form_id=64951).

# Group Observation

## Retrieve weather observation [/observation?locatedAt={locatedAt}&fields={fields}&]

#### Example
`https://api.weather.mg/observation?location=53,13`

### Observed weather for a given *latitude* and *longitude* [GET]

This resource provides data from existing weather observation stations.
These are the latest values/parameters they provide.
For any requested location a relevant station is computed.
To the relevant station, the distance and available parameters are taken into concern.

+ Parameters
    + locatedAt: `13.37788,52.5337` (string, required) - longitude,latitude; can occur multiple times for multiple stations
    + locatedAt: `joionluqqFvwqmo629nC` (string, optional) - compressed list of station locations, using Microsoft Point Compression Algorithm, is efficient for up to 400 locations
    + fields: `sunshineDurationInMinutes,airTemperatureInCelsius` (string, required) - comma separated list of parameters to be contained inside response
    + observedFromUtc: `2016-10-13T11:00:00Z` (string, optional)
    + observedUntilUtc: `2016-10-13T15:00:00Z` (string, optional)
    + observedFromLocalTime: `2016-10-13T11:00:00Z` (string, optional)
    + observedUntilLocalTime: `2016-10-13T15:00:00Z` (string, optional)
    + observedPeriod: `PT0S,PT1H,PT12H` (string, required) - comma separated list of periods to be retrieved. use iso8601 time duration notation. PT0S refers to observations at a moment in time. PT1H applies one hour aggregation.

+ Response 200 (application/json)

    + Headers

            X-Request-Calls-Per-Interval: 4711
            E-Tag: "x234dff"
            Cache-Control: max-age=3628800

                "items" : [
                    {
                        "location" : {
                            "latitude": 52.5337,
                            "longitude": 13.37788,
                        },
                        "relevantStation" : {
                            "meteoGroupStationId" : "abcd1234ef5678",
                            "stationName" : "Berlin Dahlem",
                            "longitude" : 13.12156,
                            "latitude" : 52.57113
                            "timeZoneName" : "Europe/Berlin"
                        },
                        "observation" : [
                            {
                                "observedFromUtc": "2016-10-13T11:00:00Z",
                                "observedUntilUtc": "2016-10-13T12:00:00Z",
                                "observedPeriod" : "PT1H",
                                "sunshineDurationInMinutes": 15,
                                "windGustInKnots" : 20,
                            },
                            {
                                "observedFromUtc": "2016-10-13T06:00:00Z",
                                "observedUntilUtc": "2016-10-13T18:00:00Z",
                                "observedPeriod" : "PT12H",
                                "sunshineDurationInMinutes": 123,
                                "windGustInKnots" : 20,
                            },
                            {
                                "observedFromUtc": "2016-10-13T12:00:00Z",
                                "observedUntilUtc": "2016-10-13T12:00:00Z",
                                "observedPeriod" : "PT0S",
                                "airTemperatureInCelsius": 29.6,
                                "windSpeedInKnots" : 14
                            }

                        ]
                    }
                ]
            }

# Group Forecast

## Retrieve weather forecast [/forecast?locatedAt={locatedAt}&fields={fields}&validPeriod={validPeriod}&validFrom={validFrom}{&validUntil}]

### Forecasted weather for a given *latitude* and *longitude* [GET]

Weather forecast for the next 7 days.

+ Parameters
    + locatedAt: `13.37788,52.5337` (string, required) - longitude,latitude; can occur multiple times for multiple locations
    + locatedAt: `joionluqqFvwqmo629nC` (string, optional) - compressed list of station locations, using Microsoft Point Compression Algorithm, is efficient for up to 400 locations
    + fields: `airTemperatureInCelsius,dewPointTemperatureInFahrenheit,dewPointTemperatureInKelvin` (string, required) - comma separated list of parameters to be contained inside response
    + validFromUtc: `2016-10-13T11:00:00Z` (string, optional)
    + validUntilUtc: `2016-10-13T15:00:00Z` (string, optional)
    + validFromLocalTime: `2016-10-13T11:00:00Z` (string, optional)
    + validUntilLocalTime: `2016-10-13T15:00:00Z` (string, optional)
    + validPeriod: `PT0S,PT1H,PT6H` - comma separated list of periods to be retrieved. use iso8601 time duration notation. PT1H refers one hour forecast periods. PT6H applies three hours aggregation.

+ Response 200 (application/json)

    + Headers

            X-Request-Calls-Per-Interval: 4712
            E-Tag: "a987dff"
            Cache-Control: max-age=600

    + Body

            {
                "items" : [
                {
                    "location" : {
                        "latitude": 52.5337,
                        "longitude": 13.37788,
                        "timeZoneName" : "Europe/Berlin"
                    },
                    "relevantStation" : {
                        "meteoGroupStationId" : "abcd1234ef5678",
                        "stationName" : "Berlin Dahlem",
                        "longitude" : 13.12156,
                        "latitude" : 52.57113
                    },
                    "forecast": [
                        {
                            "validFromUtc": "2016-08-25T14:00:00Z",
                            "validUntilUtc": "2016-08-25T14:00:00Z",
                            "validPeriod": "PT0S"
                            "airTemperatureInCelsius": 15.8,
                            "dewPointTemperatureInFahrenheit": 15.8,
                            "dewPointTemperatureInKelvin": 15.8,
                            "airPressureInHpa": 1012.9,
                            "effectiveCloudCoverInOcta": 3
                            "precipitationIntensityInMillimeterPerHour": 0,
                            "windSpeedInKnots":3,
                        },
                        {
                            "validFromUtc": "2016-08-25T14:00:00Z",
                            "validUntilUtc": "2016-08-25T15:00:00Z",
                            "validPeriod": "PT1H"
                            "minAirTemperatureInCelsius": 15.8,
                            "maxAirTemperatureInCelsius": 15.8,
                            "sunshineDurationInMinutes": 23,
                            "precipitationAmountInMillimeter": 0,
                            "windGustInKnots": 5,
                        },
                        {
                            "validFromUtc": "2016-08-25T14:00:00Z",
                            "validUntilUtc": "2016-08-25T20:00:00Z",
                            "validPeriod": "PT6H"
                            "minAirTemperatureInCelsius": 15.8,
                            "maxAirTemperatureInCelsius": 18.1,
                            "sunshineDurationInMinutes": 385,
                            "precipitationAmountInMillimeter": 0,
                            "windGustInKnots": 6,
                        }
                    ]
                }
            }


# Group Warning

## Retrieve severe weather warnings [/warnings?location={latitudeInDegree,longitudeInDegree}]

### Example
`https://api.weather.mg/forecast?location=53,13`

### Severe Weather Warnings [GET]

THIS IS A DRAFT.

+ Parameters
    + latitudeInDegree: `52.13` (number, required)                - latitude in degree numeric format and in range <-90,90> eg. -85.541, 5.32
    + longitudeInDegree: `13.2` (number, required)                - longitude in degree numeric format and in range <-180,180> eg. -123.454, 179.864

+ Request

    + Headers

            X-Authentication: <API-Key>
            X-TraceId: <Trace-Id>

+ Response 200 (application/json)

    + Headers

            X-Request-Calls-Per-Interval: 4712
            E-Tag: "a987dff"
            Cache-Control: max-age=600

    + Body

            {
                "location" : {
                    "latitude": 52.5337,
                    "longitude": 13.37788,
                },
                "warningId": "1234-5678",
                "issueAt": "2016-08-03T00:00:00+02:00",
                "validAt": "2016-08-03T00:00:00+02:00",
                "warningSeverity": "HIGH",
                "affectedRegion": {
                    "name": "London"
                }
            }


# Data Structures

## Backward compatibility

Weather API may add more parameters in the future.
Clients should irgnore unknown parameters.
Only when parameters will fundamently change, a new version might be introduced.

## Forecast Intervals

The response contains different time intervals which contain forecast in for different time spans.

Interval name  | Time interval  | Time span
---------------|----------------|--------------------------------
hourly         | 1 hour         | using time zone from requested location, today from 00:00 until 00:00 next day, plus 1 day ahead, means 48 hours in total
interval6hours | 6 hours        | using time zone from requested location, today from 00:00 until 00:00 next day, plus 6 days ahead, means 28 intervals in total
halfDaily      | 12 hours       | using time zone from requested location, today from 00:00 until 00:00 next day, plus 6 days ahead, means 14 intervals in total
daily          | 24 hours       | using time zone from requested location, today from 00:00 until 00:00 next day, plus 6 days ahead, means 7 days in total


## Units

Parameter | unit
---------------|-----
minAirTemperature                         | Degree or Fahrenheit
maxAirTemperature                         | Degree or Fahrenheit
airTemperature                            | Degree or Fahrenheit
dewPointTemperature                       | Degree or Fahrenheit
precipitation                             | mm or inch
precipitationLastHour                     | mm or inch
windSpeed                                 | m/s or km/h or m/h or BFT
windGust                                  | in Knots or m/h or km/h
date, time, time offset                   | timestamps including date, time and a zime offset are encoded in [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601).
precipitationProbabilityInPercent100based | a percentage which refers to the amount of precipitation probability


## Total Cloud Cover (number)

This symbolic letter shall embrace the total fraction of the celestial dome covered by clouds irrespective of their genus.
(WMO akronym 'N')

    Value | Meaning
    ------|---------
    0 | 0
    1 | 1 okta or less, but not zero
    2 | 2 oktas
    3 | 3 oktas
    4 | 4 oktas
    5 | 5 oktas
    6 | 6 oktas
    7 | 7 oktas
    8 | 8 oktas
    9 | Sky obscured by fog and/or other meteorological phenomena
