FORMAT: 1A

Weather API
=============================

**Work in Progress** - MeteoGroup's public weather API documentation

Do you want to send [feedback](https://meteogroup.zendesk.com/hc/en-gb/requests/new?ticket_form_id=64951)?

[Roadmap for Weather API](https://github.com/MeteoGroup/weather-api/tree/roadmap)

# General information

This technical document was created for developers who are creating applications based on weather data provided by this API.


The Weather API resolves weather data based on location specified by latitude and longitude coordinates.
For weather parameters prediction API offer ["forecast" endpoint](#forecast) and for weather history parameters API offer ["observation" endpoint](#observation).


This document is using [API blueprint format](https://apiblueprint.org/documentation/).


All endpoints are **secured** with HTTP basic authorization and data are transmitted over HTTPS protocol.
If you want to get access please use [request form](https://meteogroup.zendesk.com/hc/en-gb/requests/new?ticket_form_id=64951).

# Group Observation

## Retrieve weather observation [/observation?location={latitudeInDegree,longitudeInDegree}{&speedUnit}{&temperatureUnit}{&precipitationUnit}]

#### Example
`https://api.weather.mg/observation?location=53,13`

### Observed weather for a given *latitude* and *longitude* [GET]

This resource provides data from existing weather observation stations. These are the latest values/parameters they provide.
For any requested location a relevant station is computed.
For the relevance the stations distance, height difference and available parameters are taken into concern.

**This endpoint returns dummy data for now.**

+ Parameters
    + latitudeInDegree: `47.4593` (number, required)       - latitude in degree numeric format and in range <-90,90> eg. -85.541, 5.32
    + longitudeInDegree: `-2.2323` (number, required)      - longitude in degree numeric format and in range <-180,180> eg. -123.454, 179.864
    + speedUnit: `METER_PER_SECOND` (string, optional)     - select which unit for windSpeed, windGust, etc.; valid values: METER_PER_SECOND, MILES_PER_HOUR, KILOMETER_PER_HOUR, BEAUFORT, KNOT
    + temperatureUnit: `DEGREE_CELSIUS` (string, optional) - select which unit for airTemperature, etc.; valid values: DEGREE_CELSIUS, DEGREE_FAHRENHEIT
    + precipitationUnit: `MILLIMETER` (string, optional)   - select which unit for precipitation, etc.; valid values: MILLIMETER, INCH
    + visibilityUnit: `METER` (string, optional)           - select which unit for visiblity, etc.; valid values: METER, KILOMETER, NAUTICAL_MILE, STATUTE_MILE

+ Response 200 (application/json)

    + Headers

            X-Request-Calls-Per-Interval: 4711
            E-Tag: "x234dff"
            Cache-Control: max-age=3628800

    + Body

            {
              "location": {
                "latitude": 47.4593,
                "longitude": -2.2323
              },
              "observedAt": "2016-10-04T12:24:19Z",
              "airTemperature": {
                "value": 19.7,
                "unit": "DEGREE_CELSIUS"
              },
              "feelsLikeTemperature": {
                "value": 23.5,
                "unit": "DEGREE_CELSIUS"
              },
              "airPressureInHpa": 1012.9,
              "windSpeed": {
                "value": 4.7,
                "unit": "METER_PER_SECOND",
                "timeIntervalInMinutes": 10
              },
              "windGust": {
                "value": 4.8872223,
                "unit": "METER_PER_SECOND",
                "timeIntervalInMinutes": 60
              },
              "windDirectionInDegree": 210,
              "dewPointTemperature": {
                "value": 17.8,
                "unit": "DEGREE_CELSIUS"
              },
              "precipitation": {
                "value": 0.2,
                "unit": "MILLIMETER",
                "timeIntervalInMinutes": 60
              },
              "relativeHumidityInPercent100based": 89,
              "effectiveCloudCoverInOcta": 5,
              "visibility": {
                "value": 2000.0,
                "unit": "METER"
              },
              "pressureTendencyCodeForPastHour": 6,
              "presentWeather" : {
                "description" : "SHOWER(S) OF HAIL, OR OF RAIN AND HAIL; DURING THE PRECEDING HOUR BUT NOT AT THE TIME OF OBSERVATION",
                "code" : 27
              },
              "sunshineDurationInHoursForPast24Hours": 5.5,
              "weatherSymbol": 120010
            }

# Group Observation/Locations

## Retrieve weather observation [/observation?locations={compressedLocations}{&temperatureUnit}{&windSpeedUnit}{&visibilityUnit}{&precipitationUnit}]

#### Example
`https://api.weather.mg/observation?locations=joionluqqFvwqmo629nC`

### Observed weather for a given *locations* [GET]

This resource provides data from existing weather observation stations. These are the latest values/parameters they provide.
For any requested location a relevant station is computed.
For the relevance the stations distance, height difference and available parameters are taken into concern.

**This endpoint returns dummy data for now.**

+ Parameters
    + locations: `joionluqqFvwqmo629nC` (string, required) - compressed list of station locations
    + speedUnit: `METER_PER_SECOND` (string, optional)     - select which unit for windSpeed, windGust, etc.; valid values: METER_PER_SECOND, MILES_PER_HOUR, KILOMETER_PER_HOUR, BEAUFORT, KNOT
    + temperatureUnit: `DEGREE_CELSIUS` (string, optional) - select which unit for airTemperature, etc.; valid values: DEGREE_CELSIUS, DEGREE_FAHRENHEIT
    + precipitationUnit: `MILLIMETER` (string, optional)  - select which unit for precipitation, etc.; valid values: MILLIMETER, INCH
    + visibilityUnit: `METER` (string, optional)          - select which unit for visiblity, etc.; valid values: METER, KILOMETER, NAUTICAL_MILE, STATUTE_MILE

+ Response 200 (application/json)

    + Headers

            X-Request-Calls-Per-Interval: 4711
            E-Tag: "x234dff"
            Cache-Control: max-age=3628800

    + Body

            [
              {
                "location": {
                  "latitude": 18.666666,
                  "longitude": 78.1
                },
                "observedAt": "2016-10-13T11:28:42Z",
                "airTemperature": {
                  "value": 29.6,
                  "unit": "DEGREE_CELSIUS"
                },
                "feelsLikeTemperature": {
                  "value": 40,
                  "unit": "DEGREE_CELSIUS"
                },
                "airPressureInHpa": 1005.5,
                "windSpeed": {
                  "value": 0,
                  "unit": "METER_PER_SECOND",
                  "timeIntervalInMinutes": 10
                },
                "windGust": {
                  "value": 0.1,
                  "unit": "METER_PER_SECOND",
                  "timeIntervalInMinutes": 60
                },
                "windDirectionInDegree": 0,
                "dewPointTemperature": {
                  "value": 23.5,
                  "unit": "DEGREE_CELSIUS"
                },
                "precipitation": {
                  "value": 0,
                  "unit": "MILLIMETER",
                  "timeIntervalInMinutes": 60
                },
                "relativeHumidityInPercent100based": 89,
                "effectiveCloudCoverInOcta": 1,
                "visibility": {
                  "value": 10000,
                  "unit": "METER"
                },
                "pressureTendencyCodeForPastHour": 2,
                "presentWeather": {
                  "description": "STATE OF SKY ON THE WHOLE UNCHANGED",
                  "code": 2
                },
                "sunshineDurationInHoursForPast24Hours": 15.5,
                "weatherSymbol": 121000
              },
              {
                "location": {
                  "latitude": 37.5,
                  "longitude": 34.05
                },
                "observedAt": "2016-10-13T11:28:42Z",
                "airTemperature": {
                  "value": 24.8,
                  "unit": "DEGREE_CELSIUS"
                },
                "feelsLikeTemperature": {
                  "value": 23.8,
                  "unit": "DEGREE_CELSIUS"
                },
                "airPressureInHpa": 1508,
                "windSpeed": {
                  "value": 2.6,
                  "unit": "METER_PER_SECOND",
                  "timeIntervalInMinutes": 10
                },
                "windGust": {
                  "value": 0,
                  "unit": "METER_PER_SECOND",
                  "timeIntervalInMinutes": 60
                },
                "windDirectionInDegree": 260,
                "dewPointTemperature": {
                  "value": 2.3,
                  "unit": "DEGREE_CELSIUS"
                },
                "precipitation": {
                  "value": 0.1,
                  "unit": "MILLIMETER",
                  "timeIntervalInMinutes": 60
                },
                "relativeHumidityInPercent100based": 71,
                "effectiveCloudCoverInOcta": 8,
                "visibility": {
                  "value": 20000,
                  "unit": "METER"
                },
                "pressureTendencyCodeForPastHour": 7,
                "presentWeather": {
                  "description": "STATE OF SKY ON THE WHOLE UNCHANGED",
                  "code": 2
                },
                "sunshineDurationInHoursForPast24Hours": 12,
                "weatherSymbol": 100000
              }
            ]

# Group Forecast

## Retrieve weather forecast [/forecast?location={latitudeInDegree,longitudeInDegree}{&speedUnit}{&temperatureUnit}{&precipitationUnit}]

#### Example
`https://api.weather.mg/forecast?location=53,13`

### Forecasted weather for a given *latitude* and *longitude* [GET]

Weather forecast for the next 7 days.

+ Parameters
    + latitudeInDegree: `52.13` (number, required)               - latitude in degree numeric format and in range <-90,90> eg. -85.541, 5.32
    + longitudeInDegree: `13.2` (number, required)               - longitude in degree numeric format and in range <-180,180> eg. -123.454, 179.864
    + speedUnit: `METER_PER_SECOND` (string, optional)           - select which unit for windSpeed, windGust, etc.; valid values: METER_PER_SECOND, MILES_PER_HOUR, KILOMETER_PER_HOUR, BEAUFORT, KNOT
    + temperatureUnit: `DEGREE_CELSIUS` (string, optional)       - select which unit for airTemperature, etc.; valid values: DEGREE_CELSIUS, DEGREE_FAHRENHEIT
    + precipitationUnit: `MILLIMETER` (string, optional)         - select which unit for precipitation, etc.; valid values: MILLIMETER, INCH

+ Response 200 (application/json)

    + Headers

            X-Request-Calls-Per-Interval: 4712
            E-Tag: "a987dff"
            Cache-Control: max-age=600

    + Body

            {
                "location" : {
                    "latitude": 52.5337,
                    "longitude": 13.37788,
                    "timeZoneName" : "Europe/Berlin"
                },
                "forecasts": {
                    "hourly" : [
                        {
                            "validAt": "2016-08-25T14:00:00+02:00",
                            "airTemperature": {
                                "value" : 29,
                                "unit" : "DEGREE_CELSIUS"
                            },
                            "dewPointTemperature": {
                                "value" : 15.8,
                                "unit" : "DEGREE_CELSIUS"
                            },
                            "airPressureInHpa": 1012.9,
                            "sunshineDurationPastIntervalInMinutes": 23,
                            "precipitationPastInterval": {
                                "value" : 0,
                                "unit" : "MILLIMETER"
                            },
                            "precipitationProbabilityInPercent100based": 0,
                            "averageWindSpeed": {
                                "value" : 7.48,
                                "unit" : "METER_PER_SECOND"
                            },
                            "windGust" : {
                                "value" : 21.6,
                                "unit" : "METER_PER_SECOND",
                            },
                            "windDirectionInDegree": 274,
                            "effectiveCloudCoverInOcta": 3
                        }
                    ],
                    "12hourly" : [
                        {
                            "validAt": "2016-08-25T06:00:00+02:00",
                            "averageWindSpeed": {
                                "value" : 7.48,
                                "unit" : "METER_PER_SECOND"
                            },
                            "airTemperatureMax" : {
                                "value" : 22,
                                "unit" : "DEGREE_CELSIUS"
                            },
                            "airTemperatureMin" : {
                                "value" : 18,
                                "unit" : "DEGREE_CELSIUS"
                            }
                        },
                        {
                            "validAt": "2016-08-25T18:00:00+02:00",
                            "averageWindSpeed": {
                                "value" : 7.48,
                                "unit" : "METER_PER_SECOND"
                            },
                            "airTemperatureMax" : {
                                "value" : 12,
                                "unit" : "DEGREE_CELSIUS"
                            },
                            "airTemperatureMin" : {
                                "value" : 9,
                                "unit" : "DEGREE_CELSIUS"
                            }
                        }
                    ],
                    "daily" : [
                        {
                            "validAt": "2016-08-25T06:00:00+02:00",
                            "airTemperature": {
                                "value" : 29,
                                "unit" : "DEGREE_CELSIUS"
                            },
                            "airTemperatureMax" : {
                                "value" : 22,
                                "unit" : "DEGREE_CELSIUS"
                            },
                            "airTemperatureMin" : {
                                "value" : 9,
                                "unit" : "DEGREE_CELSIUS"
                            }
                            "dewPointTemperature": {
                                "value" : 15.8,
                                "unit" : "DEGREE_CELSIUS"
                            },
                            "airPressureInHpa": 1012.9,
                            "sunshineDurationPastIntervalInMinutes": 23,
                            "precipitationPastInterval": {
                                "value" : 0,
                                "unit" : "MILLIMETER"
                            },
                            "precipitationProbabilityInPercent100based": 0,
                            "averageWindSpeed": {
                                "value" : 7.48,
                                "unit" : "METER_PER_SECOND"
                            },
                            "windGust" : {
                                "value" : 21.6,
                                "unit" : "METER_PER_SECOND"
                            },
                            "windDirectionInDegree": 274,
                            "effectiveCloudCoverInOcta": 3
                        }
                    ]
                }
            }


# Group Warning

## Retrieve severe weather warnings [/warnings?location={latitudeInDegree,longitudeInDegree}]

### Example
`https://api.weather.mg/forecast?location=53,13`

### Severe Weather Warnings [GET]

THIS IS A DRAFT.

+ Parameters
    + latitudeInDegree: `52.13` (number, required)                - latitude in degree numeric format and in range <-90,90> eg. -85.541, 5.32
    + longitudeInDegree: `13.2` (number, required)                - longitude in degree numeric format and in range <-180,180> eg. -123.454, 179.864

+ Request

    + Headers

            X-Authentication: <API-Key>
            X-TraceId: <Trace-Id>

+ Response 200 (application/json)

    + Headers

            X-Request-Calls-Per-Interval: 4712
            E-Tag: "a987dff"
            Cache-Control: max-age=600

    + Body

            {
                "location" : {
                    "latitude": 52.5337,
                    "longitude": 13.37788,
                },
                "warningId": "1234-5678",
                "issueAt": "2016-08-03T00:00:00+02:00",
                "validAt": "2016-08-03T00:00:00+02:00",
                "warningSeverity": "HIGH",
                "affectedRegion": {
                    "name": "London"
                }
            }


# Data Structures

## Backward compatibility

Weather API may add more parameters in the future.
Clients should irgnore unknown parameters.
Only when parameters will fundamently change, a new version might be introduced.

## Forecast Intervals

The response contains different time intervals which contain forecast in for different time spans.

Interval name  | Time interval  | Time span
---------------|----------------|--------------------------------
hourly         | 1 hour         | using time zone from requested location, today from 00:00 until 00:00 next day, plus 1 day ahead, means 48 hours in total
interval6hours | 6 hours        | using time zone from requested location, today from 00:00 until 00:00 next day, plus 6 days ahead, means 28 intervals in total
halfDaily      | 12 hours       | using time zone from requested location, today from 00:00 until 00:00 next day, plus 6 days ahead, means 14 intervals in total
daily          | 24 hours       | using time zone from requested location, today from 00:00 until 00:00 next day, plus 6 days ahead, means 7 days in total


## Units

Parameter | unit
---------------|-----
minAirTemperature                         | Degree or Fahrenheit
maxAirTemperature                         | Degree or Fahrenheit
airTemperature                            | Degree or Fahrenheit
dewPointTemperature                       | Degree or Fahrenheit
precipitation                             | mm or inch
precipitationLastHour                     | mm or inch
windSpeed                                 | m/s or km/h or m/h or BFT
windGust                                  | in Knots or m/h or km/h
date, time, time offset                   | timestamps including date, time and a zime offset are encoded in [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601).
precipitationProbabilityInPercent100based | a percentage which refers to the amount of precipitation probability


## Total Cloud Cover (number)

This symbolic letter shall embrace the total fraction of the celestial dome covered by clouds irrespective of their genus.
(WMO akronym 'N')

    Value | Meaning
    ------|---------
    0 | 0
    1 | 1 okta or less, but not zero
    2 | 2 oktas
    3 | 3 oktas
    4 | 4 oktas
    5 | 5 oktas
    6 | 6 oktas
    7 | 7 oktas
    8 | 8 oktas
    9 | Sky obscured by fog and/or other meteorological phenomena
